name: C Samples CI

on: [push, pull_request]

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install build essential
      run: sudo apt-get install -y build-essential

    - name: build
      working-directory: ci
      run: ./build.sh
